apiVersion: v1
kind: Service
metadata:
    name: "newcluster-c787"
    labels:
        app: "newcluster-c787"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "newcluster-c787"